// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResumeBuilder.Infrastructure.Data;

#nullable disable

namespace ResumeBuilder.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ResumeBuilder.Domain.Entities.EducationDetail", b =>
                {
                    b.Property<int>("EducationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FieldOfStudy")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal?>("GPA")
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<bool>("IsCurrentlyStudying")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ResumeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("EducationId");

                    b.HasIndex("ResumeId");

                    b.ToTable("EducationDetails");
                });

            modelBuilder.Entity("ResumeBuilder.Domain.Entities.ExperienceDetail", b =>
                {
                    b.Property<int>("ExperienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Description")
                        .HasMaxLength(3000)
                        .HasColumnType("varchar(3000)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("ResumeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ExperienceId");

                    b.HasIndex("ResumeId");

                    b.ToTable("ExperienceDetails");
                });

            modelBuilder.Entity("ResumeBuilder.Domain.Entities.JobRole", b =>
                {
                    b.Property<int>("JobRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("ExperienceLevel")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("MaxSalary")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("MinSalary")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("RequiredSkills")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("JobRoleId");

                    b.HasIndex("IsActive");

                    b.ToTable("JobRoles");

                    b.HasData(
                        new
                        {
                            JobRoleId = 1,
                            Category = "IT",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Develop and maintain web applications using both frontend and backend technologies.",
                            ExperienceLevel = "Mid",
                            IsActive = true,
                            MaxSalary = 120000m,
                            MinSalary = 60000m,
                            RequiredSkills = "C#,ASP.NET,JavaScript,React,SQL Server,HTML,CSS,Git",
                            RoleName = "Full Stack Developer",
                            UpdatedAt = new DateTime(2026, 1, 29, 4, 25, 20, 507, DateTimeKind.Utc).AddTicks(8814)
                        },
                        new
                        {
                            JobRoleId = 2,
                            Category = "IT",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Create responsive user interfaces and implement frontend logic.",
                            ExperienceLevel = "Entry",
                            IsActive = true,
                            MaxSalary = 85000m,
                            MinSalary = 45000m,
                            RequiredSkills = "JavaScript,React,Angular,Vue.js,HTML,CSS,TypeScript,Git",
                            RoleName = "Frontend Developer",
                            UpdatedAt = new DateTime(2026, 1, 29, 4, 25, 20, 507, DateTimeKind.Utc).AddTicks(8823)
                        },
                        new
                        {
                            JobRoleId = 3,
                            Category = "IT",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Design and develop server-side applications and APIs.",
                            ExperienceLevel = "Mid",
                            IsActive = true,
                            MaxSalary = 110000m,
                            MinSalary = 55000m,
                            RequiredSkills = "C#,ASP.NET Core,Python,Java,SQL Server,PostgreSQL,Redis,Docker",
                            RoleName = "Backend Developer",
                            UpdatedAt = new DateTime(2026, 1, 29, 4, 25, 20, 507, DateTimeKind.Utc).AddTicks(8826)
                        },
                        new
                        {
                            JobRoleId = 4,
                            Category = "Data Science",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Analyze complex data and build machine learning models.",
                            ExperienceLevel = "Senior",
                            IsActive = true,
                            MaxSalary = 150000m,
                            MinSalary = 80000m,
                            RequiredSkills = "Python,Machine Learning,TensorFlow,PyTorch,SQL,Statistics,Data Analysis,R",
                            RoleName = "Data Scientist",
                            UpdatedAt = new DateTime(2026, 1, 29, 4, 25, 20, 507, DateTimeKind.Utc).AddTicks(8829)
                        },
                        new
                        {
                            JobRoleId = 5,
                            Category = "IT",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Implement and manage CI/CD pipelines and cloud infrastructure.",
                            ExperienceLevel = "Mid",
                            IsActive = true,
                            MaxSalary = 130000m,
                            MinSalary = 70000m,
                            RequiredSkills = "Docker,Kubernetes,AWS,Azure,Jenkins,Terraform,Linux,Git,Python",
                            RoleName = "DevOps Engineer",
                            UpdatedAt = new DateTime(2026, 1, 29, 4, 25, 20, 507, DateTimeKind.Utc).AddTicks(8832)
                        },
                        new
                        {
                            JobRoleId = 6,
                            Category = "IT",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Develop mobile applications for iOS and Android platforms.",
                            ExperienceLevel = "Mid",
                            IsActive = true,
                            MaxSalary = 115000m,
                            MinSalary = 55000m,
                            RequiredSkills = "Swift,Kotlin,React Native,Flutter,iOS,Android,REST API,Git",
                            RoleName = "Mobile App Developer",
                            UpdatedAt = new DateTime(2026, 1, 29, 4, 25, 20, 507, DateTimeKind.Utc).AddTicks(8834)
                        },
                        new
                        {
                            JobRoleId = 7,
                            Category = "Design",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Design user interfaces and create engaging user experiences.",
                            ExperienceLevel = "Entry",
                            IsActive = true,
                            MaxSalary = 90000m,
                            MinSalary = 40000m,
                            RequiredSkills = "Figma,Adobe XD,Sketch,UI Design,UX Research,Prototyping,HTML,CSS",
                            RoleName = "UI/UX Designer",
                            UpdatedAt = new DateTime(2026, 1, 29, 4, 25, 20, 507, DateTimeKind.Utc).AddTicks(8837)
                        },
                        new
                        {
                            JobRoleId = 8,
                            Category = "Management",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lead and manage software development projects and teams.",
                            ExperienceLevel = "Senior",
                            IsActive = true,
                            MaxSalary = 140000m,
                            MinSalary = 75000m,
                            RequiredSkills = "Agile,Scrum,JIRA,Communication,Leadership,Project Planning,Risk Management",
                            RoleName = "Project Manager",
                            UpdatedAt = new DateTime(2026, 1, 29, 4, 25, 20, 507, DateTimeKind.Utc).AddTicks(8839)
                        },
                        new
                        {
                            JobRoleId = 9,
                            Category = "IT",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Design and implement cloud solutions and architecture.",
                            ExperienceLevel = "Lead",
                            IsActive = true,
                            MaxSalary = 180000m,
                            MinSalary = 100000m,
                            RequiredSkills = "AWS,Azure,GCP,Kubernetes,Docker,Terraform,Security,Networking",
                            RoleName = "Cloud Architect",
                            UpdatedAt = new DateTime(2026, 1, 29, 4, 25, 20, 507, DateTimeKind.Utc).AddTicks(8842)
                        },
                        new
                        {
                            JobRoleId = 10,
                            Category = "IT",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ensure software quality through testing and automation.",
                            ExperienceLevel = "Entry",
                            IsActive = true,
                            MaxSalary = 80000m,
                            MinSalary = 40000m,
                            RequiredSkills = "Selenium,TestNG,JUnit,API Testing,Automation,Manual Testing,Git,SQL",
                            RoleName = "QA Engineer",
                            UpdatedAt = new DateTime(2026, 1, 29, 4, 25, 20, 507, DateTimeKind.Utc).AddTicks(8844)
                        });
                });

            modelBuilder.Entity("ResumeBuilder.Domain.Entities.Resume", b =>
                {
                    b.Property<int>("ResumeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("GitHubUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("LinkedInUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PortfolioUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Summary")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("ResumeId");

                    b.HasIndex("UserId");

                    b.ToTable("Resumes");
                });

            modelBuilder.Entity("ResumeBuilder.Domain.Entities.ResumeJobMatch", b =>
                {
                    b.Property<int>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("JobRoleId")
                        .HasColumnType("int");

                    b.Property<decimal>("MatchScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("MatchedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MatchedSkills")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("MissingSkills")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("ResumeId")
                        .HasColumnType("int");

                    b.HasKey("MatchId");

                    b.HasIndex("JobRoleId");

                    b.HasIndex("ResumeId", "JobRoleId")
                        .IsUnique();

                    b.ToTable("ResumeJobMatches");
                });

            modelBuilder.Entity("ResumeBuilder.Domain.Entities.Skill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("ProficiencyLevel")
                        .HasColumnType("int");

                    b.Property<int>("ResumeId")
                        .HasColumnType("int");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("SkillId");

                    b.HasIndex("ResumeId");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("ResumeBuilder.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ResumeBuilder.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ResumeBuilder.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResumeBuilder.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ResumeBuilder.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ResumeBuilder.Domain.Entities.EducationDetail", b =>
                {
                    b.HasOne("ResumeBuilder.Domain.Entities.Resume", "Resume")
                        .WithMany("EducationDetails")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("ResumeBuilder.Domain.Entities.ExperienceDetail", b =>
                {
                    b.HasOne("ResumeBuilder.Domain.Entities.Resume", "Resume")
                        .WithMany("ExperienceDetails")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("ResumeBuilder.Domain.Entities.ResumeJobMatch", b =>
                {
                    b.HasOne("ResumeBuilder.Domain.Entities.JobRole", "JobRole")
                        .WithMany("ResumeMatches")
                        .HasForeignKey("JobRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResumeBuilder.Domain.Entities.Resume", "Resume")
                        .WithMany("JobMatches")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobRole");

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("ResumeBuilder.Domain.Entities.Skill", b =>
                {
                    b.HasOne("ResumeBuilder.Domain.Entities.Resume", "Resume")
                        .WithMany("Skills")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("ResumeBuilder.Domain.Entities.JobRole", b =>
                {
                    b.Navigation("ResumeMatches");
                });

            modelBuilder.Entity("ResumeBuilder.Domain.Entities.Resume", b =>
                {
                    b.Navigation("EducationDetails");

                    b.Navigation("ExperienceDetails");

                    b.Navigation("JobMatches");

                    b.Navigation("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
